services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: qwer1234!@
    volumes:
      - ./db/conf:/etc/mysql/conf.d
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: [ 'CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD' ]
      interval: 10s
      timeout: 5s
      retries: 3

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true

      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://db:3306/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keyc1@ak

      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      - start
      - --features=preview
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
