POST /api/auth/test-realm/refresh
Host: localhost:20100
Content-Type: application/json

{
  "clientId": "portal-cli",
  "refreshToken": "eyJhbGciOiJIUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJjZmRjYWMzOS04MDYyLTQ4MDAtOGVhMS04ZjBmYjViOGQyNTkifQ.eyJleHAiOjE3MjQ2ODk3OTEsImlhdCI6MTcyNDY4Nzk5MSwianRpIjoiNWJjNmNlMjctZmJhNi00ZGYzLWE1MzktODA5ZmE4MzNhZGRmIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy90ZXN0LXJlYWxtIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL3JlYWxtcy90ZXN0LXJlYWxtIiwidHlwIjoiUmVmcmVzaCIsImF6cCI6InBvcnRhbC1jbGkiLCJzaWQiOiI4NzIyNjA2Yy0yZWIwLTQ3ZTgtYTZhYS1hZTlhZDNhOTllNTIiLCJzY29wZSI6IiJ9.EVKf9oKunIy6yvGC_OjgA-FDqjvgeui5F19YI6J7pSJOjTwT7lBqgvC2Lz7Si5saMo6LveUffKSd_L8xOEwzuA"
}
